<?php
/**
 * Created by PhpStorm.
 * User: victo
 * Date: 26/09/2017
 * Time: 13:37
 */

namespace App\Helpers;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class TransportElementHelper
{
    public function getTodaysElements()
    {
        return DB::select("
SELECT SEQ,
       ADDRESS_FROM,
       ADDRESS_STOP1,
       ADDRESS_STOP2,
       ADDRESS_STOP3,
       ADDRESS_TO,
       CONCAT(COALESCE(DATEPLANNED1, AFKOPPELDATE, AANKOPPELDATE, SHOWDATEPLANNED) , ' ', COALESCE(TIMEPLANNED1, AFKOPPELTIME, AANKOPPELTIME, SHOWTIMEPLANNED))
   FROM TRANSPORTELEMENT
   WHERE ADDRESS_FROM = 'CTT'
     AND IE = 'T'
	 AND COALESCE(DATEPLANNED1, AFKOPPELDATE, AANKOPPELDATE, SHOWDATEPLANNED) = '". Carbon::now()->format('Y-m-d') ."'
        ");
    }


    public function getMonthsElements()
    {
        return DB::select("
SELECT DISTINCT
       ADDRESS_TO.ZIPCODE || ' ' || ADDRESS_TO.CITY || ' ' || ADDRESS_TO.COUNTRY1 \"ADDRESS_TO\",
       ADDRESS_FROM.ZIPCODE || ' ' || ADDRESS_FROM.CITY || ' ' || ADDRESS_FROM.COUNTRY1 \"ADDRESS_FROM\",
       ADDRESS_FROM_CODE,
       ADDRESS_TO_CODE
FROM
  (
  SELECT ADDRESS_FROM \"ADDRESS_FROM_CODE\",
          COALESCE(ADDRESS_STOP1,ADDRESS_TO, ADDRESS_STOPSHOW) \"ADDRESS_TO_CODE\"
   FROM TRANSPORTELEMENT
   WHERE ADDRESS_FROM = 'CTT'
     AND IE = 'T'
     AND COALESCE(TRANSPORTELEMENT.DATEPLANNED1, TRANSPORTELEMENT.AFKOPPELDATE, TRANSPORTELEMENT.SHOWDATEPLANNED) >= TRUNC(SYSDATE, 'MONTH')
  
   UNION SELECT ADDRESS_STOP1 \"ADDRESS_FROM_CODE\",
                COALESCE(ADDRESS_STOP2, ADDRESS_TO, ADDRESS_STOPSHOW) \"ADDRESS_TO_CODE\"
   FROM TRANSPORTELEMENT
   WHERE ADDRESS_STOP1 IS NOT NULL
     AND ADDRESS_FROM = 'CTT'
     AND IE = 'T'
     AND COALESCE(TRANSPORTELEMENT.DATEPLANNED1, TRANSPORTELEMENT.AFKOPPELDATE, TRANSPORTELEMENT.SHOWDATEPLANNED) >= TRUNC(SYSDATE, 'MONTH')
  
   UNION SELECT ADDRESS_STOP2 \"ADDRESS_FROM_CODE\",
                COALESCE(ADDRESS_STOP3, ADDRESS_TO, ADDRESS_STOPSHOW) \"ADDRESS_TO_CODE\"
   FROM TRANSPORTELEMENT
   WHERE ADDRESS_STOP2 IS NOT NULL
     AND ADDRESS_FROM = 'CTT'
     AND IE = 'T'
     AND COALESCE(TRANSPORTELEMENT.DATEPLANNED1, TRANSPORTELEMENT.AFKOPPELDATE, TRANSPORTELEMENT.SHOWDATEPLANNED) >= TRUNC(SYSDATE, 'MONTH')
   
   UNION SELECT ADDRESS_STOP3 \"ADDRESS_FROM_CODE\",
                COALESCE(ADDRESS_TO, ADDRESS_STOPSHOW) \"ADDRESS_TO_CODE\"
   FROM TRANSPORTELEMENT
   WHERE ADDRESS_STOP3 IS NOT NULL
     AND ADDRESS_FROM = 'CTT'
     AND IE = 'T'
     AND COALESCE(TRANSPORTELEMENT.DATEPLANNED1, TRANSPORTELEMENT.AFKOPPELDATE, TRANSPORTELEMENT.SHOWDATEPLANNED) >= TRUNC(SYSDATE, 'MONTH') 
     
 ) TRANSPORTELEMENT
     
LEFT OUTER JOIN ADDRESS AS ADDRESS_TO 
  ON ADDRESS_TO.CODE = ADDRESS_TO_CODE
  
LEFT OUTER JOIN ADDRESS AS ADDRESS_FROM
  ON ADDRESS_FROM.CODE = ADDRESS_FROM_CODE
  
WHERE ADDRESS_FROM_CODE IS NOT NULL
  AND ADDRESS_TO_CODE IS NOT NULL
        ");
    }

}